### ISSUE TITLE
unable to install 1.31 from GitHub

### ISSUE THREAD

**Issue by clach04** [mwarning/trigger#10] opened 2019-02-12 16:25 UTC
I can successfully install Fdroid https://f-droid.org/repo/com.example.trigger_130.apk

I cannot install https://github.com/mwarning/trigger/releases/tag/v1.3.1

**Comment by mwarning** [comment] 2019-02-12 16:46
I rebuild the apk using `./gradlew assembleRelease`. Let's if that helps. I am new to Android.

**Comment by clach04** [comment] 2019-02-12 20:54
I've no idea what F-Droid do differently. I just downloaded 1.31 again in case you meant you had rebuilt (its identical to the one from earlier today.

I can wait until the F-Droid build of 1.31 and report back. I'm using Android 8 for testing.

**Comment by clach04** [comment] 2019-02-12 20:59
Tried an Android 5.0.1 device. Fails too, but with (maybe more information); "Problem parsing package"

**Comment by Akito13** [comment] 2019-02-12 21:28
> 
> 
> Tried an Android 5.0.1 device. Fails too, but with (maybe more information); "Problem parsing package"

As far as I recall, this happened to another app I tried to update, as well, so it might be an issue with F-Droid.

**Comment by mwarning** [comment] 2019-02-12 21:53
@clach04 yes, I rebuild the 1.3.1 apk again. If the binary is identical, then it must be the result of the build.

**Comment by mwarning** [comment] 2019-02-20 01:26
I do not know what the problem is and I do not know if the problem still exists. So I close the issue for now until this problem occurs again.

**Closed by mwarning** 2019-02-20 01:26 UTC

**Comment by clach04** [comment] 2019-07-06 18:19
From #14 Android 5.0 o nwards should work, I can not install apks from https://github.com/mwarning/trigger/releases on the two devices I've tested with. Android 5 and Android 8.

I can install F-Droid builds from https://f-droid.org/en/packages/com.example.trigger/ (or using the app) on both devices.

I get no useful information why the install fails :-( What debugging/logging can I do to work out what the problem is? Anything I can do on device or do I need to attempt to load via adb?

**Comment by clach04** [comment] 2019-07-06 18:30
I installed Stanley from https://f-droid.org/en/packages/fr.xgouchet.packageexplorer/ and it claims that `packageInfo` is null when I open the Trigger 1.9.0 (and 1.7.1) apk from github. Opening the Trigger apk (1.7.1) from FDroid works fine.

**Comment by clach04** [comment] 2019-07-06 18:32
Is the apk signed?

**Comment by mwarning** [comment] 2019-07-06 18:37
The apks are not signed. Do you at least get to the install screen with the install button? You need to allow installation of apks from an unknown source. But you should get a warning from Android telling you that (iirc).

**Comment by mwarning** [comment] 2019-07-06 19:21
Please let me know if you can tell me how to build an apk that works for you (you are probably not alone, but I can do only very limited testing with my LineageOS).

Btw., release builds are tricky because the linter flags a lot of stuff, but it is hard to figure everything out.

**Comment by mwarning** [comment] 2019-07-07 08:54
Stanley also gives me "Error: packageInfo must not be null". So far I can reproduce the problem. I will try to fix the error.

**Comment by mwarning** [comment] 2019-07-07 10:10
@clach04 I have added a signed apk: https://github.com/mwarning/trigger/releases/tag/v1.9.0
Stanley does not throw an error anymore.

**Comment by clach04** [comment] 2019-07-07 18:14
> Please let me know if you can tell me how to build an apk that works for you (you are probably not alone, but I can do only very limited testing with my LineageOS).

Sadly I have no idea :-(


> @clach04 I have added a signed apk: https://github.com/mwarning/trigger/releases/tag/v1.9.0
> Stanley does not throw an error anymore.

Thanks for doing that.
No luck I'm afraid :-( I tried on two devices.

Android 8 complained about Play Protection, (different from unknown-sources), once I disabled that it failed with not helpful message text :-(

Android 5, I disabled Play protection ahead of time. After accepting new permissions it claimed to be "installing" for a long time and then eventually did not install with "App not installed" and no explanation :-(

I'm not sure what to suggest, I'm happy to do more tests though.

**Comment by clach04** [comment] 2019-07-07 19:01
Just tried on a friend's 8.0.0 device, same behavior and no useful error messages :-(

**Comment by clach04** [comment] 2019-07-07 19:11
Tried on an Amazon Fire Tablet with same behavior, error "App not installed"

**Comment by clach04** [comment] 2019-07-07 19:22
I wonder how FDroid builds using https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.example.trigger.yml - what is it doing (and possibly not doing)?

**Comment by mwarning** [comment] 2019-07-09 15:54
@clach04 I asked someone to try to install the apk. But it failed the way you described it. No idea about the cause of it yet.

**Comment by mwarning** [comment] 2019-07-09 18:35
@clach04 please try https://github.com/mwarning/trigger/releases/tag/v1.9.1
I think I have found the problem. Previous apks were not signed or signed with the new v2 signature (only supported by android >=7.0).

**Comment by clach04** [comment] 2019-07-09 21:42
@mwarning nice! 👍 

Generally positive results with one exception and some things to be aware of.

Installs fine on a device that does NOT have Trigger previously installed, works with:

  * Android 8 - with Google Play store - NOTE google Play Protect does kick in so needs to be disabled/ignored (note sure what causes this, Stanley indicates a cert but shows `Dummy`, its possibly this causes that)
  * Amazon Fire Tablet, FireOS 5.6.4.0

Failed to install on:

  * Same Android 8 device above, when Fdroid built Trigger was installed - no useful information/message from Android installer
  * Android 5.0 device with F-Droid Trigger installed. Fails with helpful message, `App not installed. An existing package by the same name  with a conflicting signature is already installed` - screen shot ![Screenshot_android5_failure_with_existing_fdroid](https://user-images.githubusercontent.com/424032/60925037-6ca33300-a257-11e9-86d5-356d74f34948.png)
  * Android 5.0 device with F-Droid Trigger removed - fails with no useful message, based on above. Looks like minimum is now Android 7?

I do wonder if my problems with the first 1.9.1 signed build test would have been resolved by removing the existing install of Trigger. Android 5.0 support would be really nice but I don't have a pressing need at the moment (and I can install an older build).

Annoyingly non of the versions I had installed support backup/export but they do now and backup/export worked great.

**Comment by clach04** [comment] 2019-07-09 21:48
* Just tried the initial 1.9.1 signed apk from 1.9.0 release (not the official 1.9.1 build) on Android 5.0 and that did not work.
 * 1.8.0 release did not install into Android 5.0 device either.

**Comment by mwarning** [comment] 2019-07-10 08:40
Thank you a lot for testing.
I have build an apk with the v1 signature only. Maybe Android 5 does not like the v2 signature.

**Comment by clach04** [comment] 2019-07-11 05:28
I tried the v1 sig on Android 5, no luck :-( I tried to upgrade an FDroid build and got the same warning about different certs. Removed FDroid and then attempted install, but go the not helpful did not install message.

I've not had chance to try it on any other devices. I'll try and get that done tomorrow.

**Comment by mwarning** [comment] 2019-07-11 23:03
I tried trigger-1.9.1.apk (v1+v2 sig) on a emulated Android 5. It installed fine.
